# Overwritting configs
metadata: sentence
lr: 0.001

# Config the sentence embedding model
sent_emb_model: /root/autodl-tmp/MemOPSD/sentence-t5-base
sent_emb_dim: 768
sent_emb_pca: 128
# openai_api_key is only needed when sent_emb_model is text-embedding-3-large
openai_api_key: ~

sent_emb_batch_size: 512

# Config for the backbone model
max_item_seq_len: 50
n_embd: 448
n_layer: 4
n_head: 2
n_inner: 1024
activation_function: gelu_new
resid_pdrop: 0.0
embd_pdrop: 0.5
attn_pdrop: 0.5
layer_norm_epsilon: 1e-12
initializer_range: 0.02

# Semantic ID configs
n_codebook: 32
codebook_size: 256
opq_use_gpu: False
opq_gpu_id: 0
faiss_omp_num_threads: 32

# RPG configs
#   model
temperature: 0.03
num_beams: 50
n_edges: 50
propagation_steps: 3
#   decoding graph construction
chunk_size: 1024
num_workers: 64
